network:
  version: 2
  ethernets:
    ens160:
      dhcp4: false
      addresses:
      -  10.31.139.248/24
      routes:
        - to: default
          via: 10.31.139.1
      nameservers:
          addresses: [10.31.135.10, 10.31.135.20]
